### ISSUE TITLE
Image 0.0.39 missing from docker hub

### ISSUE THREAD

**Issue by mwienk** [a1tan/argocdsecretsynchronizer#4]
Hey @a1tan, it seems that image 0.0.39 is referenced from the config/default folder, but it isn't available on docker hub. Should it be 0.0.38 or did you perhaps forget to push the latest release?

**Comment by a1tan** [comment]
Hi @mwienk, it had to be 0.0.38. I have fixed it. Let me know if there is another problem.

**Comment by mwienk** [comment]
Great, thanks!
